In [44]:
import torch

In [45]:
t1= torch.tensor(4.)
t1

tensor(4.)

In [46]:
## Vector Tensor
t2 =  torch.tensor([2., 3, 5, 7])
print(t2.dtype)

t2 =  torch.tensor([2, 3, 5, 7])
print(t2.dtype)   ##All the variables of tensor have same dtype

torch.float32
torch.int64


In [47]:
##Matrix Tensor
t3 = torch.tensor ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t3

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [48]:
## 3D Array
t4 = torch.tensor([   [[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                     
                      [[1, 3, 5],
                      [2, 4, 6],
                      [3, 6, 9]]   ])
t4

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 3, 5],
         [2, 4, 6],
         [3, 6, 9]]])

In [49]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [50]:
print(t2)
t2.shape

tensor([2, 3, 5, 7])


torch.Size([4])

In [51]:
print(t3)
t3.shape

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


torch.Size([3, 3])

In [52]:
print(t4)
t4.shape

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 3, 5],
         [2, 4, 6],
         [3, 6, 9]]])


torch.Size([2, 3, 3])

In [53]:
## Tensors can't be created in improper shape
t4 = torch.tensor([   [[1, 2, 3],
                      [4, 5, 6],
                      [7, 8]],
                     
                      [[1, 3, 5],
                      [2, 4, 6],
                      [3, 6, 9]]   ])
t4

ValueError: expected sequence of length 3 at dim 2 (got 2)

In [65]:
x= torch.tensor(3.)  #Answer of derivative wrt x will be None
w= torch.tensor(4., requires_grad = True)
b= torch.tensor(5., requires_grad = True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [66]:
#Arithmatic Operations

y= w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [67]:
## Computing Derivative
y.backward()    ##It computes derivatives and store them

In [68]:
print('d/dw :', x.grad)
print('d/dx :', w.grad)
print('d/db :', b.grad)

d/dw : None
d/dx : tensor(3.)
d/db : tensor(1.)


In [77]:
t6 = torch.full((3,3),42.)
t6

tensor([[42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.]])

In [78]:
## Concatinating two tensors
t7 = torch.cat((t3,t6))
t7.dtype

torch.float32

In [79]:
#Compute sin of each element
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0.6570,  0.9894,  0.4121],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165]])

In [84]:
#Change the shape of a tensor
t9 = t8.reshape(3,3,2)
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568],
         [-0.9589, -0.2794]],

        [[ 0.6570,  0.9894],
         [ 0.4121, -0.9165],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

# 3 PyTorch functions

In [85]:
t10 = torch.acosh(t7)
t10

tensor([[0.0000, 1.3170, 1.7627],
        [2.0634, 2.2924, 2.4779],
        [2.6339, 2.7687, 2.8873],
        [4.4307, 4.4307, 4.4307],
        [4.4307, 4.4307, 4.4307],
        [4.4307, 4.4307, 4.4307]])

In [100]:
print(torch.randint(0, 30,[2 ,3, 3]))

tensor([[[29,  5,  6],
         [11, 25, 20],
         [25, 20, 22]],

        [[28,  5, 10],
         [ 3, 14, 26],
         [16, 18,  6]]])


In [101]:
print(torch.randn([2 ,3, 3]))

tensor([[[-0.8788, -0.6091,  2.9944],
         [ 0.7735, -0.8139, -1.3345],
         [ 0.3852, -0.4327, -0.1187]],

        [[-0.1020,  0.9763,  1.6990],
         [-1.6015,  0.9239,  0.0681],
         [ 0.2793, -0.4617, -1.6159]]])


In [108]:
print(torch.split(t7, 2))

(tensor([[1., 2., 3.],
        [4., 5., 6.]]), tensor([[ 7.,  8.,  9.],
        [42., 42., 42.]]), tensor([[42., 42., 42.],
        [42., 42., 42.]]))


# Inter operability with other Libraties

In [109]:
import numpy as np

In [110]:
x = np.array([[1, 2.], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [113]:
#Converting numpy array to pytorch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [112]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [117]:
#Converting tensor into numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])